import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '../components/providers/ThemeProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: {
    default:
      'Visor Ciudadano | Monitor de Seguridad y Mapa del Delito Perú 2025',
    template: '%s | Visor Ciudadano Perú',
  },
  keywords: [
    'Seguridad Ciudadana Perú',
    'Mapa del delito Lima',
    'Distritos más peligrosos Perú 2025',
    'Estadísticas PNP',
    'Denuncias policiales',
    'Robo y Extorsión Perú',
    'Semáforo delictivo',
    'Datos abiertos gobierno Perú',
  ],
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="scroll-smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-50 dark:bg-slate-950 relative`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
